name: CI

on:
  push:
    branches:
      - main

jobs:
  render_json:
    name: Render JSON
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Jsonnet
        run: sudo apt-get install -y jsonnet
      - name: Render JSON
        run: .github/scripts/render_json.sh ./jsonnet ./json
      - name: Stage Changes
        run: git add .
      - name: Commit and Push Rendered JSON
        env:
          COMMIT_USER_NAME: github-actions[bot]
          COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MESSAGE: "[AUTO] Render JSON"
          COMMIT_AUTHOR: rux616 <5643061+rux616@users.noreply.github.com>
        run: |
          if [ -n "$(git diff --staged)" ]; then
            git -c user.name="${COMMIT_USER_NAME}" -c user.email="${COMMIT_USER_EMAIL}" commit -m "${COMMIT_MESSAGE}" --author="${COMMIT_AUTHOR}"
            git push
          else
            echo "no changes to commit"
          fi
